apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: employee-service
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: employee-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: employee-service
    spec:
      containers:
      - image: docker.io/unify453/microservice-demo:employee-service
        imagePullPolicy: Always
        name: employee-service
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongo-db
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-init-credentials
              key: init.userid
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-init-credentials
              key: init.password
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: employee-service
  name: employee-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: employee-service
  type: NodePort